stages:
  download_data:
    cmd: python src/download_data.py
    deps:
      - src/download_data.py
    params:
      - data.dataset_id
    outs:
      - data/penguins.csv

  prepare_data:
    cmd: python src/prepare_data.py
    deps:
      - src/prepare_data.py
      - data/penguins.csv
    params:
      - prepare.test_size
      - prepare.random_state
    outs:
      - data/train.csv
      - data/test.csv
      - models/encoder.pkl

  train_model:
    cmd: python src/train_model.py
    deps:
      - src/train_model.py
      - data/train.csv
      - data/test.csv
    # params:
    #   - model.n_estimators
    #   - model.max_depth
    #   - model.min_samples_split
    #   - model.min_samples_leaf
    # outs:
    #   - models/model.pkl
    # metrics:
    #   - metrics.json:
    #       cache: false
